### ISSUE TITLE
conntracker panic: interface {} is nil, not *simplelru.entry

### ISSUE THREAD

**Issue by dxsup** [Kindling-project/kindling#118]
**Logs**
```
panic: interface conversion: interface {} is nil, not *simplelru.entry

goroutine 292 [running]:
github.com/hashicorp/golang-lru/simplelru.(*LRU).removeElement(0xc000dae4a0, 0xc00105b230)
	/root/go/pkg/mod/github.com/hashicorp/golang-lru@v0.5.4/simplelru/lru.go:172 +0x152
github.com/hashicorp/golang-lru/simplelru.(*LRU).removeOldest(0xc000dae4a0)
	/root/go/pkg/mod/github.com/hashicorp/golang-lru@v0.5.4/simplelru/lru.go:165 +0x4c
github.com/hashicorp/golang-lru/simplelru.(*LRU).Add(0xc000dae4a0, 0x1be7fa0, 0xc000a6db60, 0x1942260, 0xc002cd7340, 0xc000099e00)
	/root/go/pkg/mod/github.com/hashicorp/golang-lru@v0.5.4/simplelru/lru.go:67 +0x346
github.com/Kindling-project/kindling/collector/metadata/conntracker.(*conntrackCache).Add.func2(0xc004cac508, 0xc004cac4c8, 0xa6d301)
	/source/kindling/collector/metadata/conntracker/conntracker_cache.go:73 +0x15d
github.com/Kindling-project/kindling/collector/metadata/conntracker.(*conntrackCache).Add(0xc00105b200, 0xc004cac400, 0xc00089a100)
	/source/kindling/collector/metadata/conntracker/conntracker_cache.go:76 +0xe4
github.com/Kindling-project/kindling/collector/metadata/conntracker.(*Conntracker).updateCache(0xc00105b290, 0xc004cac400, 0x0)
	/source/kindling/collector/metadata/conntracker/conntracker.go:152 +0x8e
github.com/Kindling-project/kindling/collector/metadata/conntracker.(*Conntracker).poll.func2(0xc00089a120, 0xc00105b290)
	/source/kindling/collector/metadata/conntracker/conntracker.go:127 +0x51
created by github.com/Kindling-project/kindling/collector/metadata/conntracker.(*Conntracker).poll
	/source/kindling/collector/metadata/conntracker/conntracker.go:125 +0x13e
```

**Comment by dxsup** [comment]
The panic happens nearly every half an hour on my node. But I can't reproduce it by writing a test. The most possible cause is concurrently reading and writing on the same LRU cache. 

See the following part.
https://github.com/Kindling-project/kindling/blob/3324ca32063e9bfa8889975a20b6e81fe9a253b2/collector/metadata/conntracker/conntracker.go#L155-L172

There is an `RLock` in this `Get` function, but note that `ctr.cache.Get(k)` will modify the cache also, so the `RLock` can't really promise thread-safety. This could cause the above issue.

**Comment by dxsup** [comment]
After using `mutex.Lock` in the function `GetDNATTuple`, the problem has gone for two hours. I think this is the root cause.
